In [29]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import GridSearchCV

In [30]:
df = pd.read_csv(r"D:\data science\Data scientist\Competitions\train.csv")
dft = pd.read_csv(r"D:\data science\Data scientist\Competitions\test.csv")

In [54]:
test_feat = dft.drop('id',axis = 1)

In [56]:
test_ids = dft['id']

In [31]:
X = df.drop(['id', 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains',
                           'Dirtiness', 'Bumps', 'Other_Faults'], axis=1)
y = df[['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains',
                      'Dirtiness', 'Bumps', 'Other_Faults']]

In [32]:
X

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0            584        590     909972     909977            16            8   
1            808        816     728350     728372           433           20   
2             39        192    2212076    2212144         11388          705   
3            781        789    3353146    3353173           210           16   
4           1540       1560     618457     618502           521           72   
...          ...        ...        ...        ...           ...          ...   
19214        749        757     143210     143219            17            4   
19215        723        735    2488529    2488541           231           17   
19216          6         31    1578055    1578129           780          114   
19217          9         18    1713172    1713184           126           13   
19218       1505       1525    1733458    1733471           182           24   

       Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0                5               2274                    113   
1               54              44478                     70   
2              420            1311391                     29   
3               29               3202                    114   
4               67              48231                     82   
...            ...                ...                    ...   
19214            4               2193                    122   
19215           26              27135                    104   
19216           98              71112                     41   
19217           26              14808                     88   
19218           33              22785                     98   

       Maximum_of_Luminosity  ...  Outside_X_Index  Edges_X_Index  \
0                        140  ...           0.0059         1.0000   
1                        111  ...           0.0044         0.2500   
2                        141  ...           0.1077         0.2363   
3                        134  ...           0.0044         0.3750   
4                        111  ...           0.0192         0.2105   
...                      ...  ...              ...            ...   
19214                    140  ...           0.0044         1.0000   
19215                    133  ...           0.0065         0.7333   
19216                     94  ...           0.0199         0.1862   
19217                    132  ...           0.0068         0.7692   
19218                    143  ...           0.0083         0.6250   

       Edges_Y_Index  Outside_Global_Index  LogOfAreas  Log_X_Index  \
0             1.0000                   0.0      1.2041       0.9031   
1             1.0000                   1.0      2.6365       0.7782   
2             0.3857                   0.0      4.0564       2.1790   
3             0.9310                   1.0      2.3222       0.7782   
4             0.9861                   1.0      2.7694       1.4150   
...              ...                   ...         ...          ...   
19214         0.8000                   0.0      1.2305       0.7782   
19215         0.9216                   1.0      2.3636       1.0414   
19216         0.9554                   1.0      2.8921       1.4314   
19217         1.0000                   1.0      2.1004       1.0414   
19218         1.0000                   1.0      2.2601       1.1461   

       Log_Y_Index  Orientation_Index  Luminosity_Index  SigmoidOfAreas  
0           0.6990            -0.5000           -0.0104          0.1417  
1           1.7324             0.7419           -0.2997          0.9491  
2           2.2095            -0.0105           -0.0944          1.0000  
3           1.4314             0.6667           -0.0402          0.4025  
4           1.8808             0.9158           -0.2455          0.9998  
...            ...                ...               ...             ...  
19214       0.6021            -0.1429            0.0044          0.2901  
192

In [33]:
y

Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  Other_Faults
0           0          0         0       1          0      0             0
1           0          0         0       0          0      0             1
2           0          0         1       0          0      0             0
3           0          0         1       0          0      0             0
4           0          0         0       0          0      0             1
...       ...        ...       ...     ...        ...    ...           ...
19214       0          0         0       1          0      0             0
19215       0          0         0       0          0      0             1
19216       1          0         0       0          0      0             0
19217       0          0         0       0          0      0             1
19218       0          0         0       0          0      1             0

[19219 rows x 7 columns]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [46]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=1000,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    bootstrap=True,
    )
rf_multi_classifier = MultiOutputClassifier(rf_classifier,n_jobs = -1)



In [47]:
rf_multi_classifier.fit(X_train,y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(n_estimators=1000),
                      n_jobs=-1)

In [48]:
y_pred = rf_multi_classifier.predict(X_test)

from sklearn.metrics import classification_report,accuracy_score

accuracy_score(y_test,y_pred)

0.383281304197017

In [50]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.64      0.04      0.07       468
           1       0.66      0.41      0.50       312
           2       0.90      0.90      0.90      1020
           3       0.78      0.69      0.73       178
           4       0.43      0.06      0.11       143
           5       0.59      0.27      0.37      1446
           6       0.55      0.25      0.34      1958

   micro avg       0.70      0.38      0.49      5525
   macro avg       0.65      0.37      0.43      5525
weighted avg       0.64      0.38      0.45      5525
 samples avg       0.36      0.36      0.36      5525



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
best_test_probs = rf_multi_classifier.fit(X_train,y_train).predict_proba(test_feat)
best_test_probs

[array([[0.647, 0.353],
        [0.672, 0.328],
        [1.   , 0.   ],
        ...,
        [1.   , 0.   ],
        [0.602, 0.398],
        [1.   , 0.   ]]),
 array([[0.987, 0.013],
        [0.976, 0.024],
        [0.931, 0.069],
        ...,
        [1.   , 0.   ],
        [0.945, 0.055],
        [0.994, 0.006]]),
 array([[1.   , 0.   ],
        [0.976, 0.024],
        [0.95 , 0.05 ],
        ...,
        [0.076, 0.924],
        [0.966, 0.034],
        [0.13 , 0.87 ]]),
 array([[1.   , 0.   ],
        [1.   , 0.   ],
        [0.999, 0.001],
        ...,
        [1.   , 0.   ],
        [1.   , 0.   ],
        [1.   , 0.   ]]),
 array([[0.961, 0.039],
        [0.8  , 0.2  ],
        [1.   , 0.   ],
        ...,
        [1.   , 0.   ],
        [0.894, 0.106],
        [0.999, 0.001]]),
 array([[0.838, 0.162],
        [0.812, 0.188],
        [0.689, 0.311],
        ...,
        [1.   , 0.   ],
        [0.829, 0.171],
        [1.   , 0.   ]]),
 array([[0.617, 0.383],
        [0.617, 0.383]

In [57]:
import time
submission_df = pd.DataFrame({'id': test_ids})
for i, target in enumerate(y_train.columns):
    submission_df[target] = best_test_probs[i][:, 1]  
    time.sleep(6)
    print(submission_df) 
submission_df.to_csv('D:\data science\Data scientist\Competitions\Submission.csv', index=False)

          id  Pastry
0      19219   0.353
1      19220   0.328
2      19221   0.000
3      19222   0.189
4      19223   0.009
...      ...     ...
12809  32028   0.075
12810  32029   0.080
12811  32030   0.000
12812  32031   0.398
12813  32032   0.000

[12814 rows x 2 columns]
          id  Pastry  Z_Scratch
0      19219   0.353      0.013
1      19220   0.328      0.024
2      19221   0.000      0.069
3      19222   0.189      0.032
4      19223   0.009      0.022
...      ...     ...        ...
12809  32028   0.075      0.132
12810  32029   0.080      0.013
12811  32030   0.000      0.000
12812  32031   0.398      0.055
12813  32032   0.000      0.006

[12814 rows x 3 columns]
          id  Pastry  Z_Scratch  K_Scatch
0      19219   0.353      0.013     0.000
1      19220   0.328      0.024     0.024
2      19221   0.000      0.069     0.050
3      19222   0.189      0.032     0.000
4      19223   0.009      0.022     0.000
...      ...     ...        ...       ...
12809  32028   0.0